# version: '3.8'

# services:
#   spring-boot-app:
#     image: openjdk:21-jdk-slim
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./target/blog.application-0.0.1-SNAPSHOT.jar:/app/blog.application-0.0.1-SNAPSHOT.jar
#     command: ["java", "-jar", "/app/blog.application-0.0.1-SNAPSHOT.jar"]

version: '3.8'

services:
  spring-boot-app:
    image: openjdk:21-jdk-slim
    volumes:
      - ./target/blog.application-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/app.jar"]
